version: '2'

services:
  redis:
    image: redis:alpine
    volumes:
      - ./data-redis:/data
    expose:
      - 6379

  tracker:
    build: .
    depends_on:
      - redis
    ports:
      - "8080:80"